### ISSUE TITLE
Seeing these errors in the logs

### ISSUE THREAD

**Issue by rossphillips70** [blandman/node-red-unofficial-sense#2]
FetchError: invalid json response body at https://api.sense.com/apiservice/api/v1/app/monitors/211471/devices reason: Unexpected token < in JSON at position 0
0|node-red  |     at /home/node-red/node_modules/node-fetch/lib/index.js:272:32
0|node-red  |     at runMicrotasks (<anonymous>)
0|node-red  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|node-red  |     at async /home/node-red/node_modules/unofficial-sense/index.js:70:42 {
0|node-red  |   message: 'invalid json response body at https://api.sense.com/apiservice/api/v1/app/monitors/211471/devices reason: Unexpected token < in JSON at position 0',
0|node-red  |   type: 'invalid-json'

**Comment by alexsahka** [comment]
Same here, a lot of errors in Node-Red log. Is this "healthy"?

**Comment by alexsahka** [comment]
So this project is dead?
